name: ndt_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  quickalert: ^1.0.2
  shimmer: ^3.0.0
  youtube_player_flutter: ^8.1.2
  fluid_dialog: ^2.0.0


dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/home/
    - assets/images/game/
    - assets/images/questions/
