name: ndt_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+7

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  carousel_slider: ^5.1.1
  chat_gpt_sdk: ^2.2.5
  dash_chat_2: ^0.0.19
  device_preview: ^1.1.0
  dot_navigation_bar: ^1.0.2
  fluid_dialog: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  flutter_riverpod: ^2.4.5
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  quickalert: ^1.0.2
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: null
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/splash.png
  color_dark: "#121212"
  image_dark: assets/images/splash/splash.png
  
  android_12:
    image: assets/images/splash/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash/splash.png
    icon_background_color_dark: "#121212"

  web: false
dependency_overrides: 
  intl: ^0.19.0
  
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/home/
    - assets/images/game/
    - assets/images/questions/
    - assets/images/chat/
